### ISSUE TITLE
Issue with scrolling and layout shift caused by flipcard element

### ISSUE THREAD

**Issue by ibweb** [forrestkirby/flipcard-element#22] opened 2021-04-09 01:58 UTC
When using multiple flipcard elements within a multi-column format, we are seeing extremely odd behavior on scrolling to different sections later in the page.  The page is jumping violently (for lack of a better description).  

1. Go to https://www.ignitingbusiness.com/ via Chrome on a MOBILE device (note that this is NOT visually replicable on DevTools in Chrome from our tests).  Note I used a Pixel 4a for the test.
2. Interact with the flip cards.
3. Scroll down to "located in Kansas City and Serving Clients Nationally" section
4. You will see the section violent jumping.
5. In addition, the following errors are in Console (replicable on Chrome when set to a Pixel 2 or other mobile device):
hd-flipcard.js?2.4.9:38 [Intervention] Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
(anonymous) @ hd-flipcard.js?2.4.9:38
hd-flipcard.js?2.4.9:38 [Intervention] Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
(anonymous) @ hd-flipcard.js?2.4.9:38

Finally, you can also go to this page https://www.ignitingbusiness.com/lees-summit-mo which also has flipcard and similar (but less extreme behavior)

We only have this issue on pages with the FlipCard element being used.

Note that this is high priority on our end as it significantly negatively affects the user experience and likely CLS (cumulative layout shift) as well.

**Client (please complete the following information):**
 - OS: Android
 - Browser: Chrome (mobile)
 - YOOtheme Pro Version: replicated on 2.4.6 and 2.4.9 (current)
 - Custom Element Version - Latest

**Comment by ibweb** [comment] 2021-04-09 02:02
As one additional note, I did download the latest copy of Flipcard from github (rename the old previous version for a true fresh install) and still experienced the issue.  I just wanted to make sure I tested on the purest and most up-to-date version of your custome element.

**Comment by forrestkirby** [comment] 2021-04-09 06:39
Hi,

I will take a look at this and see whether I can reproduce this behaviour. Thanks for reporting and the detailed description. 

---

Regarding the JS error, this is caused by line 38 of `hd-flipcard/js/hd-flipcard.js`.

```js
e.preventDefault();
```

This line has already been removed in [this commit](https://github.com/forrestkirby/flipcard-element/commit/5de053787724f8e4c14a354287dd680878733211#diff-3aaa8e45c0ad6c21d3f96a5b50a95b631fb717fc75f9b0696782ccd0bae1e15d). You said you already downloaded the latest copy of the element from GitHub, but on both pages you shared I still see this line in the `hd-flipcard.js`.

**Comment by ibweb** [comment] 2021-04-09 13:19
@forrestkirby thanks for the quick response.
I appreciate you looking into this so quickly.  Let me know what you discover.  
----
I logged in and confirmed that hd-flipcard.js had the removal as reflected in the referenced commit.  I can verify the file is the latest and correct.
Note that as a part of troubleshooting I renamed hd-flipcard to hd-flipcard_OLD and essentially re-uploaded a fresh (latest) version of hd-flipcard.  Somehow though, it looks like it was still referencing hd-flipcard_OLD's files when you looked at the site.  As such, I removed that hd-flipcard_OLD folder, cleared all caches, and now I don't see the JS error in console.

That said, the behavior mentioned in this issue is still the same as described in my original issue report.  
Let me know if there's anything I can do to help resolve this issue since it's present on our live site (home page!).

**Comment by forrestkirby** [comment] 2021-04-09 13:21
Thank you. Could you please try https://github.com/forrestkirby/flipcard-element/tree/2.4.10 and check if the layout shift behaviour has improved?

**Comment by ibweb** [comment] 2021-04-09 13:32
@forrestkirby you are speedy!!!  I will work on rolling that out now and respond back soon.

**Comment by ibweb** [comment] 2021-04-09 13:45
@forrestkirby the changes have been rolled out, and all caches cleared.  The layout shift behavior still appears to be present (most visible/dramatic on the home page).

**Comment by forrestkirby** [comment] 2021-04-09 14:42
If you simply remove all content from `hd-flipcard/js/hd-flipcard.js` (so that this file is empty), does the issue still occur?

**Comment by ibweb** [comment] 2021-04-09 14:52
@forrestkirby oddly, yes, the issue persists even when hd-flipcard.js is empty.

**Comment by ibweb** [comment] 2021-04-09 14:54
@forrestkirby I apologize for the second follow up.  I made hd-flipcard.js blank and the issue persisted after clearing all cache.
I went ahead and put the original hd-flipcard.js file back in place.  If you need me to leave it empty for a bit if you're actively looking at it, let me know.

**Comment by forrestkirby** [comment] 2021-04-09 14:59
Ok, I’m just trying to narrow it down, because it’s hard for me to reproduce. If you additionally emtpy the file `hd-flipcard/css/hd-flipcard.css`, does the issue still occur?

**Comment by ibweb** [comment] 2021-04-09 15:10
@forrestkirby I certainly understand.  I emptied hd-flipcard.css, cleared caches, and the issues persisted.  
I also tried disabling YT Pro's lazyloading and webp images, and that had no effect.
After testing, I put the original settings and files back in place. 

Note that we do not have any JS or CSS minimization tools installed at this point (i.e. no JCH Optimize present)

If it would be easier for troubleshooting, I would be happy to provide you temporary FTP and backend access if needed.  I would need your direct contact info to do so.

**Comment by ibweb** [comment] 2021-04-09 15:11
@forrestkirby perhaps I misread your previous post, do you want BOTH the hd-flipcard.css and hd-flipcard.js file empty at the SAME time?  I only tested them empty one at a time.

**Comment by forrestkirby** [comment] 2021-04-09 15:13
If neither the CSS nor the JS causes this issue, I think it’s rather a UIkit issue or caused by the settiings. You might want to try to disable all *Match Height* and *Height Viewport* options in your layout. The autocalculation of the height of an element in combination with a vertical alignment can cause such kind of “flickering” effect due to endless re-calculations.

**Comment by forrestkirby** [comment] 2021-04-09 15:13
> perhaps I misread your previous post, do you want BOTH the hd-flipcard.css and hd-flipcard.js file empty at the SAME time? I only tested them empty one at a time.

Yes, please try removing both at the same time.

**Comment by ibweb** [comment] 2021-04-09 15:20
@forrestkirby 
we removed both at the same time.  The same issue persists.
For disabling all match height and Viewport options - this is unfortunate as it is necessary for some of our design layouts for those two pages.  Are you saying any match height setting on the entire page could cause an issue?  For example, there's a slider set at the bottom of the page even.  Could that impact it, or only any sections, rows, or elements above the affected section?
Any guidance you can provide on the above would be much appreciated.

**Comment by forrestkirby** [comment] 2021-04-09 15:29
Match Height or Height Viewport in combination with Vertical Alignment: Middle can cause such issues. I suspect the sections *Web Design, SEO, and Marketing Agency Serving Kansas City and Beyond* and *Located in Kansas City and Serving Clients Nationally*, but this is only a suspicion. It would be easier to identify if it was possible to reproduce this on a desktop PC :/ I suggest to remove sections or elements step by step each time check if the issue persists. This might help narrowing down where the issue is coming from.

Anyways, if the issue also appears without the flipcards (the flipcard is basically two panels, only the CSS and JS is creating the flip effect), it’s most probably not an issue of the element. You might want to create a question in the YOOtheme support forum. When you do so, I recommend providing admin access to a test website where the issue can be investigated and tested. You can easily create a copy of your website using Akeeba Backup and Akeeba Kickstart, for example.

**Comment by ibweb** [comment] 2021-04-09 15:39
@forrestkirby thank you for the additional info.
I spun up a test environment and found the culprit.  The Switcher element (in the "Web Design, SEO, and Marketing..." section) had "Match content Height" enabled under the Switcher settings.  We've used this setting before numerous times but never saw an issue like this, so I'm not sure what's unique about this page that caused the conflict.

I believe the page is working fine now on mobile.  Do you see any remnant of the issue on your end?

As a sidenote, I removed flipcard completely from this page on the development environment and the issue persisted, so it's likely not related to flipcard.  I would assume you agree with that statement given the above testing?

**Comment by forrestkirby** [comment] 2021-04-09 15:50
> I believe the page is working fine now on mobile. Do you see any remnant of the issue on your end?

No, I just can’t checked hte site again with Pixel 4/Chrome via Browserstack and couldn’t reproduce this anymore.

> As a sidenote, I removed flipcard completely from this page on the development environment and the issue persisted, so it's likely not related to flipcard. I would assume you agree with that statement given the above testing?

Yes, I do. I will close this issue now because we both agree that it’s not related to the element.

**Closed as completed by forrestkirby** 2021-04-09 15:50 UTC

**Comment by ibweb** [comment] 2021-04-09 15:52
@forrestkirby thanks for you excellent and super responsive help with this.  I apologize for not looking into this further on my end before jumping to thinking it was a flipcard issue.
I appreciate your help and speedy responses!

**Comment by forrestkirby** [comment] 2021-04-09 16:08
You’re welcome and thanks for the positive feedback :)
